#:schema node_modules/wrangler/config-schema.json
name = "vless2clash"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  { pattern = "sub.newbietan.cn", custom_domain = true }
]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "<YOUR_KV_NAMESPACE_ID>" }
]

[vars]
ADMIN_PASSWORD = "123456"
# TURNSTILE_SITEKEY = ""    # Cloudflare Turnstile Site Key
# TURNSTILE_SECRET_KEY = "" # Cloudflare Turnstile Secret Key

[assets]
directory = "./public"
